---
title: "Advanced Modeling Assign."
author: "Jieun Park"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Library

```{r}
library(tidyverse)
library(GGally) # ggplot2-based visualization of correlations
install.packages("factoextra")
library(factoextra) # ggplot2-based visualization of pca
library(countrycode)
library(rworldmap)
library(mice)
library(plotly)
```


## Data

```{r}
rm(list = ls())
library(readr)
fish = read.csv("./data/estat_tag00076.csv")

install.packages("stringr")
library(stringr)
library(dplyr)

# Split the combined_variable into separate variables
fish_split <- strsplit(fish$freq.species.fishreg.unit.geo.TIME_PERIOD, ",")

# Convert the list to a matrix
split_matrix <- do.call(rbind, fish_split)

# Convert the matrix to a data frame
df <- as.data.frame(split_matrix)

# Rename the columns if needed
colnames(df) <- c("frequency", "species", "fishreg", "unit", "geography")

# Print the data frame
print(df)

fish = fish |> select(-freq.species.fishreg.unit.geo.TIME_PERIOD)

fish = df |> cross_join(fish)
colnames(fish) <- c("frequency", "species", "fishreg", "unit", "geography", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022")
cleaned_fish <- fish %>%
  mutate(across(everything(), ~ ifelse(str_detect(., ":"), NA, .)))

cleaned_fish <- cleaned_fish %>%
  mutate_at(vars(6:ncol(cleaned_fish)), ~if_else(str_detect(., "[a-z]"), NA, .))

cleaned_fish = cleaned_fish %>%
  mutate_at(vars(6:ncol(cleaned_fish)), as.numeric)

cleaned_fish <- cleaned_fish %>%
  mutate_at(vars(6:ncol(cleaned_fish)), ~round(., 0))

cleaned_fish = na.omit(cleaned_fish)
fish_numeric = cleaned_fish[,6:ncol(cleaned_fish)]

# Print the resulting data frame
print(cleaned_fish)

?replace
```

## Imputation NAs

```{r}
sapply(fish_numeric, function(x) sum(is.na(x))*100/nrow(fish_numeric))


fish_numeric <- cleaned_fish[,6:ncol(cleaned_fish)]

m = 4 # number of multiple imputations, we are going to make 4 iterations, we're going to predict missing values 4 times.
mice_mod = mice(cleaned_fish, m = m, method='rf') # machine learning tool, rf = random forest
WHO <- complete(mice_mod, action=m) # replace missiong value with the mice_mod
View(WHO)

```

## PCA

```{r}
install.packages("prcomp")
library(prcomp)
table(is.na(fish_numeric))
pca = prcomp(fish_numeric, scale = TRUE)
summary(pca)

library(factoextra)

fviz_screeplot(pca, addlabels = TRUE)

barplot(pca$rotation[,1], las=2, col="darkblue")

fviz_contrib(pca, choice = "var", axes = 1)

names=cleaned_fish$geography

names[order(pca$x[,1])][1:10]
names[order(pca$x[,1], decreasing=T)][1:10]

barplot(pca$rotation[,2], las=2, col="darkblue")

names[order(pca$x[,2])][1:5]
names[order(pca$x[,2], decreasing=T)][1:5]

fviz_contrib(pca, choice = "var", axes = 2)

data.frame(z1=pca$x[,1],z2=pca$x[,2]) %>% 
  ggplot(aes(z1,z2,label=names,color=names)) + geom_point(size=0) +
  labs(title="First two principal components (scores)", x="PC1", y="PC2") + #guides(color=guide_legend(title="HDI"))+
  theme_bw() +theme(legend.position="bottom") + geom_text(size=3, hjust=0.6, vjust=0, check_overlap = TRUE) 

data.frame(z1=-pca$x[,1],country=cleaned_fish$geography) %>% group_by(country) %>% summarise(mean=mean(z1), n=n()) %>% arrange(desc(mean))

map = data.frame(country=names, value=-pca$x[,1])
#Convert the country code into iso3c using the function countrycode()
map$country = countrycode(map$country, 'country.name', 'iso3c')
#Create data object supporting the map
matched <- joinCountryData2Map(map, joinCode = "ISO3",
                               nameJoinColumn = "country")
#Draw the map
mapCountryData(matched, nameColumnToPlot="value",missingCountryCol = "white",
               addLegend = FALSE, borderCol = "#C7D9FF",
               catMethod = "pretty", colourPalette = "terrain",
               mapTitle = c("PCA1 by Country"), lwd=1)
european_countries <- subset(countryExData, EPI_regions == "Europe")

?map
```

```{r}

```















