---
title: "Notebook to download socio-economic data in the world"
author: "Advanced Modelling, Master in Computational Social Science"
date: 'UC3M, 2024'
output:
  html_document: 
    css: my-theme.css
    theme: cerulean
    highlight: tango
    number_sections: no
    toc: no
    toc_depth: 1
  pdf_document:
    css: my-theme.css
    theme: cerulean
    highlight: tango
    number_sections: yes
    toc: yes
    toc_depth: 1
editor_options:
  chunk_output_type: console
---


```{r global_options, include=T, echo = F}
knitr::opts_chunk$set(echo = T, warning=FALSE, message=FALSE)
```

```{r, echo=FALSE}
htmltools::img(src = knitr::image_uri(file.path("uc3m.jpg")), 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px;',
               width="600",
               height="80")
```

Load and prepare data from the World Health Organization (WHO) connecting through its API

Here we can browse WHO data by topic:
  https://apps.who.int/gho/data/node.main
  

```{r}
# devtools::install_github("pierucci/rgho@devel")
library(rgho)  #Api WHO
library(WDI) # API The World Bank
library(tidyverse)
library(countrycode)
library(rworldmap)
library(GGally)
```

Let's start downloading variables from WHO
  
```{r}
# Create a data frame with all countries in the world
WHO = get_gho_values(dimension = "COUNTRY") %>%
  arrange(Title)

# Regions:
#  AFR  Africa
#  AMR  Americas
#  EMR  Eastern Mediterranean
#  EUR  Europe
#  SEAR South-East Asia
#  WPR  Western Pacific

WHO = WHO %>% rename(Country=Title, COUNTRY=Code)

# WHOSIS_000001: Life expectancy at birth (years)
var = get_gho_data("WHOSIS_000001") %>% mutate(LifeExpectancy=NumericValue) %>%
  group_by(COUNTRY) %>% filter(YEAR==max(YEAR,na.rm=T)) %>% arrange(SEX) %>% slice(1) %>% 
  dplyr::select(COUNTRY, LifeExpectancy)
WHO = merge(WHO, var, by="COUNTRY", all=T)
dim(WHO)

# MDG_0000000001: Infant mortality rate (between birth and 11 months per 1000 live births)
var = get_gho_data("MDG_0000000001") %>% mutate(IMR = NumericValue) %>% 
  group_by(COUNTRY) %>% filter(YEAR==max(YEAR,na.rm=T)) %>% arrange(SEX) %>% slice(1) %>% 
  dplyr::select(COUNTRY, IMR) 
WHO = merge(WHO, var, by="COUNTRY", all=T)

# Population is taken from World Bank data bank, available through tidyr
var = filter(world_bank_pop, indicator=="SP.POP.TOTL")[,c(1,20)]
names(var) = c("COUNTRY", "Population")
var$Population = var$Population/1000
WHO = merge(WHO, var, by="COUNTRY", all=T)

# SDGPM25 : Annual mean levels of fine particulate matter (PM2.5)
var = get_gho_data("SDGPM25") %>% mutate(AirPollution = NumericValue) %>%
  group_by(COUNTRY) %>% filter(YEAR==max(YEAR,na.rm=T)) %>% slice(1) %>%
  dplyr::select(COUNTRY, AirPollution)
WHO = merge(WHO, var, by="COUNTRY", all=T)

# VIOLENCE_HOMICIDERATE: Estimates of rates of homicides per 100 000 population
var = get_gho_data("VIOLENCE_HOMICIDERATE") %>% mutate(HomicidesRate = NumericValue) %>% 
  group_by(COUNTRY) %>% filter(YEAR==max(YEAR,na.rm=T)) %>% slice(1) %>% 
  dplyr::select(COUNTRY, HomicidesRate) 
WHO = merge(WHO, var, by="COUNTRY", all=T)

# GHED_CHEGDP_SHA2011: Current health expenditure (CHE) as percentage of gross domestic product (GDP) (%)
var = get_gho_data("GHED_CHEGDP_SHA2011") %>% mutate(HealthExp = NumericValue) %>% 
  group_by(COUNTRY) %>% filter(YEAR==max(YEAR,na.rm=T)) %>% slice(1) %>% 
  dplyr::select(COUNTRY, HealthExp) 
WHO = merge(WHO, var, by="COUNTRY", all=T)

# HWF_0001: Medical doctors (per 10 000 population)
var = get_gho_data("HWF_0001") %>% mutate(MedicalDoctors = NumericValue) %>% 
  group_by(COUNTRY) %>% filter(YEAR==max(YEAR,na.rm=T)) %>% slice(1) %>% 
  dplyr::select(COUNTRY, MedicalDoctors) 
WHO = merge(WHO, var, by="COUNTRY", all=T)

# WHS6_102: Hospital beds (per 10 000 population)
var = get_gho_data("WHS6_102") %>% mutate(HospitalBeds = NumericValue) %>% 
  group_by(COUNTRY) %>% filter(YEAR==max(YEAR,na.rm=T)) %>% slice(1) %>% 
  dplyr::select(COUNTRY, HospitalBeds) 
WHO = merge(WHO, var, by="COUNTRY", all=T)

# ITU_ICT_1: Percentage of individuals using the Internet
var = get_gho_data("ITU_ICT_1") %>% mutate(Internet = NumericValue) %>% 
  group_by(COUNTRY) %>% filter(YEAR==max(YEAR,na.rm=T)) %>% slice(1) %>% 
  dplyr::select(COUNTRY, Internet) 
WHO = merge(WHO, var, by="COUNTRY", all=T)


# Other variables from The World Bank

# Literacy rate, adult total (% of people ages 15 and above)
var = WDI(indicator='SE.ADT.LITR.ZS', country="all", extra=TRUE, latest=5) %>%
  mutate(Literacy=SE.ADT.LITR.ZS, COUNTRY=iso3c) %>% 
  group_by(COUNTRY) %>% filter(year==max(year,na.rm=T)) %>% 
  dplyr::select(COUNTRY, Literacy, capital) 
WHO = merge(WHO, var, by="COUNTRY", all=T)

# Expected Years Of School
var = WDI(indicator='HD.HCI.EYRS', country="all", extra=TRUE, latest=5) %>%
  mutate(SchoolYears=HD.HCI.EYRS, COUNTRY=iso3c) %>% 
  group_by(COUNTRY) %>% filter(year==max(year,na.rm=T)) %>% 
  dplyr::select(COUNTRY, SchoolYears) 
WHO = merge(WHO, var, by="COUNTRY", all=T)

# Unemployment, total (% of total labor force)
var = WDI(indicator='SL.UEM.TOTL.ZS', country="all", extra=TRUE, latest=5) %>%
  mutate(Unemployment=SL.UEM.TOTL.ZS, COUNTRY=iso3c) %>% 
  group_by(COUNTRY) %>% filter(year==max(year,na.rm=T)) %>% 
  dplyr::select(COUNTRY, Unemployment) 
WHO = merge(WHO, var, by="COUNTRY", all=T)

# GDP per capita (constant 2015 US$)
var = WDI(indicator='NY.GDP.PCAP.KD', country="all", extra=TRUE, latest=5) %>%
  mutate(GDP=NY.GDP.PCAP.KD, COUNTRY=iso3c) %>% 
  group_by(COUNTRY) %>% filter(year==max(year,na.rm=T)) %>% 
  dplyr::select(COUNTRY, GDP) 
WHO = merge(WHO, var, by="COUNTRY", all=T)

# Names for Continents and Regions, and remove countries with no Region
WHO$Continent = countrycode(WHO$COUNTRY, "iso3c", destination="continent")
WHO$Region = countrycode(WHO$COUNTRY, "iso3c", destination="region")
WHO$Country = countrycode(WHO$COUNTRY, "iso3c", destination="country.name")
WHO = WHO %>% drop_na(Continent,Region)

WHO = WHO %>% 
  dplyr::select(Country,COUNTRY,Continent, Region, everything())
```

Write the file to load it later

```{r}
write.table(WHO, "WorldData2024.txt", sep=",")
```
